version: '3'
services:
  web:
    container_name: my-web
    build:
      context: ./
      dockerfile: Dockerfile
    image: my-web:1.0
    ports:
      - "9088:9088"
    environment:
      ENV: dev
    external_links:
      - demo:minions-service
    networks:
      minions:
        ipv4_address: 172.31.0.14
        
networks:
  minions:
    external:
      name: minions
